# CONFIG
require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - '.git/**/*'
    - 'docker/**/*'
  NewCops: enable
  TargetRubyVersion: 2.7.6
  SuggestExtensions: false

# STYLE
Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: no_comma

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

Style/OpenStructUse:
  Exclude:
    - 'spec/**/*'

Style/ClassMethodsDefinitions:
  EnforcedStyle: def_self


Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: no_comma

# LAYOUT
Layout/ArgumentAlignment:
  EnforcedStyle: with_first_argument

Layout/LineEndStringConcatenationIndentation:
  EnforcedStyle: aligned

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: aligned
  IndentationWidth: ~

Layout/HashAlignment:
  EnforcedHashRocketStyle:
    - table
    - key
  EnforcedColonStyle:
    - table
    - key

Layout/MultilineOperationIndentation:
  EnforcedStyle: aligned

# RSPEC
RSpec/NamedSubject:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/ExampleLength:
  Max: 15

RSpec/DescribeClass:
  Exclude:
    - 'spec/lib/tasks/**/*'

# LINT
Lint/MissingSuper:
  Exclude:
    - 'app/services/**/*'
    - 'app/policies/**/*'

# RAILS
Rails/SkipsModelValidations:
  Exclude:
    - 'spec/**/*'

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - staging

